def make_card(name, card_type, hp=0, damage=0, heal=0, draw=0, prize_bonus=0, shield=0):
    return {
        "name": name,
        "type": card_type,
        "hp": hp,
        "damage": damage,
        "heal": heal,
        "draw": draw,
        "prize_bonus": prize_bonus,
        "shield": shield,
    }

def get_deck_by_name(deck_name):
    decks = {
        "Deck Pikachu EX": [
            make_card("Pikachu EX", "pokemon", hp=220, damage=60),
            make_card("Raichu", "pokemon", hp=150, damage=50),
            make_card("Potion", "item", heal=30),
            make_card("Super Potion", "item", heal=50),
            make_card("Professor", "supporter", draw=2),
            make_card("Power Band", "item", damage=20),
            make_card("Energy Bolt", "energy"),
            make_card("Energy Bolt", "energy"),
            make_card("Lucky Prize", "supporter", prize_bonus=1),
            make_card("Barrier", "supporter", shield=20),
        ],
        "Deck Charizard EX": [
            make_card("Charizard EX", "pokemon", hp=330, damage=80),
            make_card("Charmander", "pokemon", hp=70, damage=20),
            make_card("Rare Candy", "item", draw=1),
            make_card("Potion", "item", heal=30),
            make_card("Burn Boost", "item", damage=25),
            make_card("Professor", "supporter", draw=2),
            make_card("Fire Energy", "energy"),
            make_card("Fire Energy", "energy"),
            make_card("Fire Energy", "energy"),
            make_card("Barrier", "supporter", shield=20),
        ],
        "Deck Chien-Pao": [
            make_card("Chien-Pao", "pokemon", hp=230, damage=70),
            make_card("Frigibax", "pokemon", hp=70, damage=20),
            make_card("Potion", "item", heal=30),
            make_card("Professor", "supporter", draw=2),
            make_card("Water Energy", "energy"),
            make_card("Water Energy", "energy"),
            make_card("Power Band", "item", damage=20),
            make_card("Lucky Prize", "supporter", prize_bonus=1),
            make_card("Barrier", "supporter", shield=20),
            make_card("Super Potion", "item", heal=50),
        ],
        "Deck Miraidon": [
            make_card("Miraidon", "pokemon", hp=220, damage=65),
            make_card("Regieleki", "pokemon", hp=140, damage=45),
            make_card("Potion", "item", heal=30),
            make_card("Professor", "supporter", draw=2),
            make_card("Electric Energy", "energy"),
            make_card("Electric Energy", "energy"),
            make_card("Power Band", "item", damage=20),
            make_card("Barrier", "supporter", shield=20),
            make_card("Lucky Prize", "supporter", prize_bonus=1),
            make_card("Super Potion", "item", heal=50),
        ],
        "Deck Gardevoir": [
            make_card("Gardevoir", "pokemon", hp=310, damage=75),
            make_card("Ralts", "pokemon", hp=60, damage=15),
            make_card("Potion", "item", heal=30),
            make_card("Super Potion", "item", heal=50),
            make_card("Professor", "supporter", draw=2),
            make_card("Psychic Energy", "energy"),
            make_card("Psychic Energy", "energy"),
            make_card("Barrier", "supporter", shield=20),
            make_card("Lucky Prize", "supporter", prize_bonus=1),
            make_card("Power Band", "item", damage=20),
        ],
    }
    return decks.get(deck_name, decks["Deck Pikachu EX"])